In [198]:
library(ade4)
library(ggbiplot)

library(tidyverse)
library(colorRamps)
library(wesanderson)
library(plotly)
library(stringr)
library(entropy)  
library(broom)
library(patchwork)
library(dplyr)

options(repr.plot.width=12, repr.plot.heigh=12)

In [199]:
my_palette <- wes_palette("FantasticFox1", 12, type = "continuous")

# Set default color and fill scales globally
update_geom_defaults("bar", list(fill = my_palette[1], color= "white"))
update_geom_defaults("col", list(fill = my_palette[2], color="white"))

scale_fill_discrete <- function(...) scale_fill_manual(values = my_palette, ...)
scale_color_discrete <- function(...) scale_color_manual(values = my_palette, ...)

In [200]:
ThemeMain<-theme( title =element_text(size=16, face='bold'),
                 axis.text.y = element_blank(), 
                 axis.text.x = element_text(color='black'),
                 axis.ticks.y = element_blank(),
                 axis.title.x = element_text(size=16,color='black',face='bold')
                 )


theme_set(theme_bw())
theme_set(ThemeMain)

In [201]:
df <- read.csv("../data/owid-energy-data.csv")

In [202]:
head(df, 5)

  country       year iso_code population gdp biofuel_cons_change_pct
1 ASEAN (Ember) 2000          NA         NA  NA
2 ASEAN (Ember) 2001          NA         NA  NA
3 ASEAN (Ember) 2002          NA         NA  NA
4 ASEAN (Ember) 2003          NA         NA  NA
5 ASEAN (Ember) 2004          NA         NA  NA
  biofuel_cons_change_twh biofuel_cons_per_capita biofuel_consumption
1 NA                      NA                      NA
2 NA                      NA                      NA
3 NA                      NA                      NA
4 NA                      NA                      NA
5 NA                      NA                      NA
  biofuel_elec_per_capita ⋯ solar_share_elec solar_share_energy
1 NA                      ⋯ 0                NA
2 NA                      ⋯ 0                NA
3 NA                      ⋯ 0                NA
4 NA                      ⋯ 0                NA
5 NA                      ⋯ 0                NA
  wind_cons_change_pct wind_cons_change_twh wind_consumption
1 NA                   NA                   NA
2 NA                   NA                   NA
3 NA                   NA                   NA
4 NA                   NA                   NA
5 NA                   NA                   NA
  wind_elec_per_capita wind_electricity wind_energy_per_capita wind_share_elec
1 NA                   0                NA                     0
2 NA                   0                NA                     0
3 NA                   0                NA                     0
4 NA                   0                NA                     0
5 NA                   0                NA                     0
  wind_share_energy
1 NA
2 NA
3 NA
4 NA
5 NA

In [203]:
RESOURCES = c("biofuel", "coal", "fossil", "gas", "hydro", "low_carbon", "nuclear", "oil",  "solar", "wind", "low_carbon", "renewables", "other_renewables")

In [204]:
COUNTRY_INFO = c("country", "year", "gdp", "iso_code", "population", "greenhouse_gas_emissions", "carbon_intensity_elec", "net_elec_imports", "net_elec_imports_share_demand", "per_capita_electricity", "electricity_demand", "electricity_generation", "electricity_share_energy", "energy_cons_change_pct", "energy_cons_change_twh", "energy_per_capita", "energy_per_gdp", "primary_energy_consumption")

In [205]:
str(df)

'data.frame':	21812 obs. of  129 variables:
 $ country                                     : chr  "ASEAN (Ember)" "ASEAN (Ember)" "ASEAN (Ember)" "ASEAN (Ember)" ...
 $ year                                        : int  2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 ...
 $ iso_code                                    : chr  "" "" "" "" ...
 $ population                                  : num  NA NA NA NA NA NA NA NA NA NA ...
 $ gdp                                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ biofuel_cons_change_pct                     : num  NA NA NA NA NA NA NA NA NA NA ...
 $ biofuel_cons_change_twh                     : num  NA NA NA NA NA NA NA NA NA NA ...
 $ biofuel_cons_per_capita                     : num  NA NA NA NA NA NA NA NA NA NA ...
 $ biofuel_consumption                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ biofuel_elec_per_capita                     : num  NA NA NA NA NA NA NA NA NA NA ...
 $ biofuel_electricity                         : num  5.87 6.46 6.62 7.45 8.4 ...
 $ biofuel_share_elec                          : num  1.55 1.6 1.53 1.63 1.69 ...
 $ biofuel_share_energy                        : num  NA NA NA NA NA NA NA NA NA NA ...
 $ carbon_intensity_elec                       : num  570 568 570 575 581 ...
 $ coal_cons_change_pct                        : num  NA NA NA NA NA NA NA NA NA NA ...
 $ coal_cons_change_twh                        : num  NA NA NA NA NA NA NA NA NA NA ...
 $ coal_cons_per_capita                        : num  NA NA NA NA NA NA NA NA NA NA ...
 $ coal_consumption                            : num  NA NA NA NA NA NA NA NA NA NA ...
 $ coal_elec_per_capita                        : num  NA NA NA NA NA NA NA NA NA NA ...
 $ coal_electricity                            : num  76 86.3 93.4 102 115 ...
 $ coal_prod_change_pct                        : num  NA NA NA NA NA NA NA NA NA NA ...
 $ coal_prod_change_twh                        : num  NA NA NA NA NA NA NA NA NA NA ...
 $ coal_prod_per_capita                        : num  NA NA NA NA NA NA NA NA NA NA ...
 $ coal_production                             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ coal_share_elec                             : num  20.1 21.3 21.6 22.3 23.2 ...
 $ coal_share_energy                           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ electricity_demand                          : num  379 405 433 458 497 ...
 $ electricity_generation                      : num  379 405 433 458 497 ...
 $ electricity_share_energy                    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ energy_cons_change_pct                      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ energy_cons_change_twh                      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ energy_per_capita                           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ energy_per_gdp                              : num  NA NA NA NA NA NA NA NA NA NA ...
 $ fossil_cons_change_pct                      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ fossil_cons_change_twh                      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ fossil_elec_per_capita                      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ fossil_electricity                          : num  305 328 357 382 419 ...
 $ fossil_energy_per_capita                    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ fossil_fuel_consumption                     : num  NA NA NA NA NA NA NA NA NA NA ...
 $ fossil_share_elec                           : num  80.7 80.9 82.3 83.3 84.3 ...
 $ fossil_share_energy                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ gas_cons_change_pct                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ gas_cons_change_twh                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ gas_consumption                             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ gas_elec_per_capita                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ gas_electricity                             : num  164 190 209 227 244 ...
 $ gas_energy_per_capita                       : num  NA NA NA NA NA NA NA NA NA NA ...
 $ gas_prod_change_pct                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ gas_prod_change_twh                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ gas_prod_per_capita                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ gas_production                              : num  NA NA NA NA NA NA NA NA NA NA ...
 $ gas_share_elec                              : num  43.4 47 48.2 49.4 49.2 ...
 $ gas_share_energy                            : num  NA NA NA NA NA NA NA NA NA NA ...
 $ greenhouse_gas_emissions                    : num  216 230 247 263 289 ...
 $ hydro_cons_change_pct                       : num  NA NA NA NA NA NA NA NA NA NA ...
 $ hydro_cons_change_twh                       : num  NA NA NA NA NA NA NA NA NA NA ...
 $ hydro_consumption                           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ hydro_elec_per_capita                       : num  NA NA NA NA NA NA NA NA NA NA ...
 $ hydro_electricity                           : num  50.5 54.3 53.3 53.2 53 ...
 $ hydro_energy_per_capita                     : num  NA NA NA NA NA NA NA NA NA NA ...
 $ hydro_share_elec                            : num  13.3 13.4 12.3 11.6 10.7 ...
 $ hydro_share_energy                          : num  NA NA NA NA NA NA NA NA NA NA ...
 $ low_carbon_cons_change_pct                  : num  NA NA NA NA NA NA NA NA NA NA ...
 $ low_carbon_cons_change_twh                  : num  NA NA NA NA NA NA NA NA NA NA ...
 $ low_carbon_consumption                      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ low_carbon_elec_per_capita                  : num  NA NA NA NA NA NA NA NA NA NA ...
 $ low_carbon_electricity                      : num  73.2 77.2 76.5 76.4 78 ...
 $ low_carbon_energy_per_capita                : num  NA NA NA NA NA NA NA NA NA NA ...
 $ low_carbon_share_elec                       : num  19.3 19.1 17.7 16.7 15.7 ...
 $ low_carbon_share_energy                     : num  NA NA NA NA NA NA NA NA NA NA ...
 $ net_elec_imports                            : num  NA NA NA NA NA NA NA NA NA NA ...
 $ net_elec_imports_share_demand               : num  NA NA NA NA NA NA NA NA NA NA ...
 $ nuclear_cons_change_pct                     : num  NA NA NA NA NA NA NA NA NA NA ...
 $ nuclear_cons_change_twh                     : num  NA NA NA NA NA NA NA NA NA NA ...
 $ nuclear_consumption                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ nuclear_elec_per_capita                     : num  NA NA NA NA NA NA NA NA NA NA ...
 $ nuclear_electricity                         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ nuclear_energy_per_capita                   : num  NA NA NA NA NA NA NA NA NA NA ...
 $ nuclear_share_elec                          : num  0 0 0 0 0 0 0 0 0 0 ...
 $ nuclear_share_energy                        : num  NA NA NA NA NA NA NA NA NA NA ...
 $ oil_cons_change_pct                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ oil_cons_change_twh                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ oil_consumption                             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ oil_elec_per_capita                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ oil_electricity                             : num  65.1 51 54.3 53.3 59.4 ...
 $ oil_energy_per_capita                       : num  NA NA NA NA NA NA NA NA NA NA ...
 $ oil_prod_change_pct                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ oil_prod_change_twh                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ oil_prod_per_capita                         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ oil_production                              : num  NA NA NA NA NA NA NA NA NA NA ...
 $ oil_share_elec                              : num  17.2 12.6 12.5 11.6 12 ...
 $ oil_share_energy                            : num  NA NA NA NA NA NA NA NA NA NA ...
 $ other_renewable_consumption                 : num  NA NA NA NA NA NA NA NA NA NA ...
 $ other_renewable_electricity                 : num  22.8 22.9 23.2 23.2 25 ...
 $ other_renewable_exc_biofuel_electricity     : num  16.9 16.4 16.6 15.7 16.6 ...
 $ other_renewables_cons_change_pct            : num  NA NA NA NA NA NA NA NA NA NA ...
 $ other_renewables_cons_change_twh            : num  NA NA NA NA NA NA NA NA NA NA ...
 $ other_renewables_elec_per_capita            : num  NA NA NA NA NA NA NA NA NA NA ...
 $ other_renewables_elec_per_capita_exc_biofuel: num  NA NA NA NA NA NA NA NA NA NA ...
  [list output truncated]

In [215]:
df_long <- df %>%
  pivot_longer(
    cols =  -all_of(COUNTRY_INFO),
    names_to = "resource_stat",
    values_to = "value"
  ) %>% 
  mutate(
    resource_stat = gsub("fossil_fuel", "fossil",
                    gsub("renewable_", "renewables_", resource_stat))
  )%>%
  mutate(
    resource = str_extract(resource_stat, str_c(RESOURCES, collapse = "|")),
    stat = str_remove(resource_stat, str_c(resource, "_"))
  )%>%
  dplyr::rename(
    country_energy_per_capita = energy_per_capita
  ) %>%
  select(-resource_stat) %>%
  pivot_wider(
    names_from = stat,
    values_from = value
  )

In [216]:
head(df_long)

  country       year iso_code population gdp carbon_intensity_elec
1 ASEAN (Ember) 2000          NA         NA  569.557
2 ASEAN (Ember) 2000          NA         NA  569.557
3 ASEAN (Ember) 2000          NA         NA  569.557
4 ASEAN (Ember) 2000          NA         NA  569.557
5 ASEAN (Ember) 2000          NA         NA  569.557
6 ASEAN (Ember) 2000          NA         NA  569.557
  electricity_demand electricity_generation electricity_share_energy
1 378.61             378.61                 NA
2 378.61             378.61                 NA
3 378.61             378.61                 NA
4 378.61             378.61                 NA
5 378.61             378.61                 NA
6 378.61             378.61                 NA
  energy_cons_change_pct ⋯ share_elec share_energy prod_change_pct
1 NA                     ⋯  1.550     NA           NA
2 NA                     ⋯ 20.081     NA           NA
3 NA                     ⋯ 80.653     NA           NA
4 NA                     ⋯ 43.385     NA           NA
5 NA                     ⋯ 13.325     NA           NA
6 NA                     ⋯ 19.347     NA           NA
  prod_change_twh prod_per_capita production energy_per_capita
1 NA              NA              NA         NA
2 NA              NA              NA         NA
3 NA              NA              NA         NA
4 NA              NA              NA         NA
5 NA              NA              NA         NA
6 NA              NA              NA         NA
  exc_biofuel_electricity elec_per_capita_exc_biofuel share_elec_exc_biofuel
1 NA                      NA                          NA
2 NA                      NA                          NA
3 NA                      NA                          NA
4 NA                      NA                          NA
5 NA                      NA                          NA
6 NA                      NA                          NA

In [223]:
df_numeric = select(df, where(is.numeric))

In [226]:
df_filled

      year population gdp         biofuel_cons_change_pct
1     2000      NA    NA          NA
2     2001      NA    NA          NA
3     2002      NA    NA          NA
4     2003      NA    NA          NA
5     2004      NA    NA          NA
6     2005      NA    NA          NA
7     2006      NA    NA          NA
8     2007      NA    NA          NA
9     2008      NA    NA          NA
10    2009      NA    NA          NA
11    2010      NA    NA          NA
12    2011      NA    NA          NA
13    2012      NA    NA          NA
14    2013      NA    NA          NA
15    2014      NA    NA          NA
16    2015      NA    NA          NA
17    2016      NA    NA          NA
18    2017      NA    NA          NA
19    2018      NA    NA          NA
20    2019      NA    NA          NA
21    2020      NA    NA          NA
22    2021      NA    NA          NA
23    2022      NA    NA          NA
24    2023      NA    NA          NA
25    1900 4707744    NA          NA
26    1901 4751177    NA          NA
27    1902 4802500    NA          NA
28    1903 4861833    NA          NA
29    1904 4921891    NA          NA
30    1905 4982681    NA          NA
⋮     ⋮    ⋮          ⋮           ⋮
21783 1994 10858598   23447496704 NA
21784 1995 10994044   23569799168 NA
21785 1996 11178171   26145775616 NA
21786 1997 11362406   27012558848 NA
21787 1998 11548365   27984297984 NA
21788 1999 11716452   27841290240 NA
21789 2000 11834679   26765004800 NA
21790 2001 11910981   26781181952 NA
21791 2002 11984643   24872480768 NA
21792 2003 12075835   20952016896 NA
21793 2004 12160885   19792844800 NA
21794 2005 12224758   18444472320 NA
21795 2006 12330490   18042998784 NA
21796 2007 12450566   17769105408 NA
21797 2008 12550353   15050245120 NA
21798 2009 12679812   16275796992 NA
21799 2010 12839774   17918418944 NA
21800 2011 13025789   19554105344 NA
21801 2012 13265331   22811426816 NA
21802 2013 13555420   23261956096 NA
21803 2014 13855758   23818844160 NA
21804 2015 14154937   24246159360 NA
21805 2016 14452705   24362051584 NA
21806 2017 14751101   25576013824 NA
21807 2018 15052191   26786273280 NA
21808 2019 15354606   25146417152 NA
21809 2020 15669663   23178706944 NA
21810 2021 15993525   25140088832 NA
21811 2022 16320539   25901586432 NA
21812 2023 16665407            NA NA
      biofuel_cons_change_twh biofuel_cons_per_capita biofuel_consumption
1     NA                      NA                      NA
2     NA                      NA                      NA
3     NA                      NA                      NA
4     NA                      NA                      NA
5     NA                      NA                      NA
6     NA                      NA                      NA
7     NA                      NA                      NA
8     NA                      NA                      NA
9     NA                      NA                      NA
10    NA                      NA                      NA
11    NA                      NA                      NA
12    NA                      NA                      NA
13    NA                      NA                      NA
14    NA                      NA                      NA
15    NA                      NA                      NA
16    NA                      NA                      NA
17    NA                      NA                      NA
18    NA                      NA                      NA
19    NA                      NA                      NA
20    NA                      NA                      NA
21    NA                      NA                      NA
22    NA                      NA                      NA
23    NA                      NA                      NA
24    NA                      NA                      NA
25    NA                      NA                      NA
26    NA                      NA                      NA
27    NA                      NA                      NA
28    NA                      NA                      NA
29    NA                      NA                      NA
30    NA                      NA                      NA
⋮     ⋮                       ⋮                       ⋮
21783 NA                      NA                      NA
21784 NA                      NA                      NA
21785 NA                      NA                      NA
21786 NA                      NA                      NA
21787 NA                      NA                      NA
21788 NA                      NA                      NA
21789 NA                      NA                      NA
21790 NA                      NA                      NA
21791 NA                      NA                      NA
21792 NA                      NA                      NA
21793 NA                      NA                      NA
21794 NA                      NA                      NA
21795 NA                      NA                      NA
21796 NA                      NA                      NA
21797 NA                      NA                      NA
21798 NA                      NA                      NA
21799 NA                      NA                      NA
21800 NA                      NA                      NA
21801 NA                      NA                      NA
21802 NA                      NA                      NA
21803 NA                      NA                      NA
21804 NA                      NA                      NA
21805 NA                      NA                      NA
21806 NA                      NA                      NA
21807 NA                      NA                      NA
21808 NA                      NA                      NA
21809 NA                      NA                      NA
21810 NA                      NA                      NA
21811 NA                      NA                      NA
21812 NA                      NA                      NA
      biofuel_elec_per_capita biofuel_electricity biofuel_share_elec ⋯
1     NA                       5.87               1.550              ⋯
2     NA                       6.46               1.596              ⋯
3     NA                       6.62               1.528              ⋯
4     NA                       7.45               1.626              ⋯
5     NA                       8.40               1.692              ⋯
6     NA                       8.80               1.684              ⋯
7     NA                       8.53               1.559              ⋯
8     NA                      10.25               1.770              ⋯
9     NA                      10.55               1.747              ⋯
10    NA                      10.88               1.742              ⋯
11    NA                      13.70               1.995              ⋯
12    NA                      15.54               2.167              ⋯
13    NA                      16.77               2.160              ⋯
14    NA                      18.03               2.208              ⋯
15    NA                      18.43               2.134              ⋯
16    NA                      19.97               2.212              ⋯
17    NA                      22.02               2.280              ⋯
18    NA                      24.28               2.417              ⋯
19    NA                      28.16               2.650              ⋯
20    NA                      28.79               2.588              ⋯
21    NA                      28.74               2.609              ⋯
22    NA                      32.48               2.834              ⋯
23    NA                      39.03               3.237              ⋯
24    NA                      40.64               3.284              ⋯
25    NA                         NA                  NA              ⋯
26    NA                         NA                  NA              ⋯
27    NA                         NA                  NA              ⋯
28    NA                         NA                  NA              ⋯
29    NA                         NA                  NA              ⋯
30    NA                         NA                  NA              ⋯
⋮     ⋮                       ⋮                   ⋮                  ⋱
21783     NA                    NA                   NA              ⋯
21784     NA                    NA                   NA              ⋯
21785     NA                    NA                   NA              ⋯
21786     NA                    NA                   NA              ⋯
21787     NA                    NA                   NA              ⋯
21788     NA                    NA                   NA              ⋯
21789  0.000                  0.00                0.000              ⋯
21790  0.000                  0.00                0.000              ⋯
21791  0.000                  0.00                0.000              ⋯
21792  0.000                  0.00                0.000              ⋯
21793  0.000                  0.00                0.000              ⋯
21794  0.000                  0.00                0.000              ⋯
21795  8.110                  0.10                1.253              ⋯
21796  4.819                  0.06                0.789              ⋯
21797  6.374                  0.08                1.048              ⋯
21798  4.732                  0.06                0.823              ⋯
21799  5.452                  0.07                0.810              ⋯
21800  6.909                  0.09                0.981              ⋯
21801  9.046                  0.12                1.311              ⋯
21802  9.590                  0.13                1.363              ⋯
21803  0.722                  0.01                0.101              ⋯
21804  2.826                  0.04                0.417              ⋯
21805 15.914                  0.23                3.208              ⋯
21806 10.169                  0.15                1.987              ⋯
21807 12.623                  0.19                2.013              ⋯
21808 12.374                  0.19                2.238              ⋯
21809  6.382                  0.10                1.490              ⋯
21810  0.000                  0.00                0.000              ⋯
21811  6.127                  0.10                1.120              ⋯
21812     NA                    NA                   NA              ⋯
      solar_share_elec solar_share_energy wind_cons_change_pct
1     0.000            NA                 NA
2     0.000            NA                 NA
3     0.000            NA                 NA
4     0.000            NA                 NA
5     0.000            NA                 NA
6     0.000            NA                 NA
7     0.007            NA                 NA
8     0.007            NA                 NA
9     0.007            NA                 NA
10    0.006            NA                 NA
11    0.010            NA                 NA
12    0.014            NA                 NA
13    0.068            NA                 NA
14    0.176            NA                 NA
15    0.257            NA                 NA
16    0.317            NA                 NA
17    0.534            NA                 NA
18    0.630            NA                 NA
19    0.647            NA                 NA
20    1.224            NA                 NA
21    1.826            NA                 NA
22    3.130            NA                 NA
23    3.086            NA                 NA
24    3.112            NA                 NA
25       NA            NA                 NA
26       NA            NA                 NA
27       NA            NA                 NA
28       NA            NA                 NA
29       NA            NA                 NA
30       NA            NA                 NA
⋮     ⋮                ⋮                  ⋮
21783    NA            NA                 NA
21784    NA            NA                 NA
21785    NA            NA                 NA
21786    NA            NA                 NA
21787    NA            NA                 NA
21788    NA            NA                 NA
21789 0.000            NA                 NA
21790 0.000            NA                 NA
21791 0.000            NA                 NA
21792 0.000            NA                 NA
21793 0.000            NA                 NA
21794 0.000            NA                 NA
21795 0.000            NA                 NA
21796 0.000            NA                 NA
21797 0.000            NA                 NA
21798 0.000            NA                 NA
21799 0.000            NA                 NA
21800 0.000            NA                 NA
21801 0.000            NA                 NA
21802 0.000            NA                 NA
21803 0.000            NA                 NA
21804 0.104            NA                 NA
21805 0.139            NA                 NA
21806 0.132            NA                 NA
21807 0.212            NA                 NA
21808 0.353            NA                 NA
21809 0.298            NA                 NA
21810 0.236            NA                 NA
21811 0.336            NA                 NA
21812    NA            NA                 NA
      wind_cons_change_twh wind_consumption wind_elec_per_capita
1     NA                   NA               NA
2     NA                   NA               NA
3     NA                   NA               NA
4     NA                   NA               NA
5     NA                   NA               NA
6     NA                   NA               NA
7     NA                   NA               NA
8     NA                   NA               NA
9     NA                   NA               NA
10    NA                   NA               NA
11    NA                   NA               NA
12    NA                   NA               NA
13    NA                   NA               NA
14    NA                   NA               NA
15    NA                   NA               NA
16    NA                   NA               NA
17    NA                   NA               NA
18    NA                   NA               NA
19    NA                   NA               NA
20    NA                   NA               NA
21    NA                   NA               NA
22    NA                   NA               NA
23    NA                   NA               NA
24    NA                   NA               NA
25    NA                   NA               NA
26    NA                   NA               NA
27    NA                   NA               NA
28    NA                   NA               NA
29    NA                   NA               NA
30    NA                   NA               NA
⋮     ⋮                    ⋮                ⋮
21783 NA                   NA               NA
21784 NA                   NA               NA
21785 NA                   NA               NA
21786 NA                   NA               NA
21787 NA                   NA               NA
21788 NA                   NA               NA
21789 NA                   NA                0
21790 NA                   NA                0
21791 NA                   NA                0
21792 NA                   NA                0
21793 NA                   NA                0
21794 NA                   NA                0
21795 NA                   NA                0
21796 NA                   NA                0
21797 NA                   NA                0
21798 NA                   NA                0
21799 NA                   NA                0
21800 NA                   NA                0
21801 NA                   NA                0
21802 NA                   NA                0
21803 NA                   NA                0
21804 NA                   NA                0
21805 NA                   NA                0
21806 NA                   NA                0
21807 NA                   NA                0
21808 NA                   NA                0
21809 NA                   NA                0
21810 NA                   NA                0
21811 NA                   NA                0
21812 NA                   NA               NA
      wind_electricity wind_energy_per_capita wind_share_elec wind_share_energy
1      0.00            NA                     0.000           NA
2      0.00            NA                     0.000           NA
3      0.00            NA                     0.000           NA
4      0.00            NA                     0.000           NA
5      0.00            NA                     0.000           NA
6      0.02            NA                     0.004           NA
7      0.05            NA                     0.009           NA
8      0.06            NA                     0.010           NA
9      0.06            NA                     0.010           NA
10     0.07            NA                     0.011           NA
11     0.10            NA                     0.015           NA
12     0.13            NA                     0.018           NA
13     0.14            NA                     0.018           NA
14     0.49            NA                     0.060           NA
15     0.62            NA                     0.072           NA
16     1.26            NA                     0.140           NA
17     1.57            NA                     0.163           NA
18     2.55            NA                     0.254           NA
19     3.47            NA                     0.327           NA
20     5.91            NA                     0.531           NA
21     5.79            NA                     0.526           NA
22     7.63            NA                     0.666           NA
23    13.09            NA                     1.086           NA
24    16.11            NA                     1.302           NA
25       NA            NA                        NA           NA
26       NA            NA                        NA           NA
27       NA            NA                        NA           NA
28       NA            NA                        NA           NA
29       NA            NA                        NA           NA
30       NA            NA                        NA           NA
⋮     ⋮                ⋮                      ⋮               ⋮
21783 NA               NA                     NA              NA
21784 NA               NA                     NA              NA
21785 NA               NA                     NA              NA
21786 NA               NA                     NA              NA
21787 NA               NA                     NA              NA
21788 NA               NA                     NA              NA
21789  0               NA                      0              NA
21790  0               NA                      0              NA
21791  0               NA                      0              NA
21792  0               NA                      0              NA
21793  0               NA                      0              NA
21794  0               NA                      0              NA
21795  0               NA                      0              NA
21796  0               NA                      0              NA
21797  0               NA                      0              NA
21798  0               NA                      0              NA
21799  0               NA                      0              NA
21800  0               NA                      0              NA
21801  0               NA                      0              NA
21802  0               NA                      0              NA
21803  0               NA                      0              NA
21804  0               NA                      0              NA
21805  0               NA                      0              NA
21806  0               NA                      0              NA
21807  0               NA                      0              NA
21808  0               NA                      0              NA
21809  0               NA                      0              NA
21810  0               NA                      0              NA
21811  0               NA                      0              NA

In [227]:
pca = prcomp(df_filled, scale. = TRUE)

ERROR: Error in svd(x, nu = 0, nv = k): infinite or missing values in 'x'

In [228]:
ggbiplot(pca, scale = 1)

ERROR: Error in ggbiplot(pca, scale = 1): object 'pca' not found